1106 move issues state from labels to projects
octoclairvoyant/octoclairvoyant-webapp pull request #1113
Opened 2022-08-21 17:30 UTC by Belco90

## Changes

- Remove `status:*` labels
- Add a new issue template for "chore" type
- Set up [add-to-project](https://github.com/actions/add-to-project) action, so issues created from templates get automatically added to the [General Project](https://github.com/orgs/octoclairvoyant/projects/2).

## Context

Closes #1106
Closes #1079 

## Tests

I've checked my work by:

- [ ] Adding new tests or adjusting existing tests
- [X] Testing manually (I need to test it after this gets merged by creating a fake issue and checking it gets added to the project)

2022-08-21 17:31 UTC, Belco90 commented on .github/workflows/add-to-project.yml
> +          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
I've already added this secret to our repo.

2022-08-22 08:13 UTC, HonkingGoose requested changes

2022-08-22 08:13 UTC, HonkingGoose commented on .github/ISSUE_TEMPLATE/chore_record.yml
> +        Changes that affect the build system, CI config or other changes that don't modify src/test files
```suggestion
        Changes that affect the build system, CI config or other changes that don't modify src/test files.
```

2022-08-22 09:04 UTC, HonkingGoose approved these changes

2022-08-22 09:04 UTC, merged